required = [
    "github.com/op/go-logging",
    "gopkg.in/mgo.v2",
    "github.com/spf13/viper",
    "github.com/ethereum/go-ethereum/cmd/abigen"
    ]
[[constraint]]
  branch = "master"
  name = "github.com/op/go-logging"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"
